services:
  http-server-projeto-korp:
    build:
      context: .
      dockerfile: Dockerfile
    image: http-server-projeto-korp:1.0.0
    restart: unless-stopped
    networks:
      - projeto-korp-network

  nginx:
    image: nginx:1.31.3-alpine
    restart: unless-stopped
    depends_on:
      - http-server-projeto-korp
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - projeto-korp-network

  prometheus:
    image: prom/prometheus:v3.12.0
    restart: unless-stopped
    depends_on:
      - http-server-projeto-korp
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - projeto-korp-network

  grafana:
    image: grafana/grafana:13.1.1
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin_password
      GF_USERS_ALLOW_SIGN_UP: "false"
    secrets:
      - grafana_admin_password
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - projeto-korp-network

volumes:
  prometheus-data:
  grafana-data:

secrets:
  grafana_admin_password:
    file: ./secrets/grafana_admin_password

networks:
  projeto-korp-network:
    external: true
    name: projeto-korp-network